title: Vinicius Artur
logo: "/images/photo.png?raw=true"
description: >
  Senior DevOps Engineer
  <br><br>
  Cloud & Infrastructure Automation
  <br><br>
  AWS, Azure, Terraform, Kubernetes,
  <br>
  CI/CD, Observability
  <br><br>
  <a href="https://www.linkedin.com/in/viniciusartur/">View My LinkedIn</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
