title: Vinicius Artur
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior DevOps Engineer
  <br><br>
  Open Source Contributor | Problem Solver 
  <br><br>
  <a href="https://www.linkedin.com/in/viniciusartur/"/>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
